# Generated by Django 3.1.6 on 2021-04-18 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_roomates', models.CharField(choices=[('Zero', 'Zero'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five')], default='Zero', max_length=100)),
                ('dorm_pref', models.CharField(choices=[('No preference.', 'None'), ('Hall-Style', 'Hall'), ('Suite-Style', 'Suite')], default='No preference.', max_length=100)),
                ('time_of_day', models.CharField(choices=[('Neither a night owl or early bird', 'Neither'), ("I'm a night owl", 'Night'), ("I'm more of a morning person", 'Morning')], default='Neither a night owl or early bird', max_length=100)),
                ('tidiness', models.CharField(choices=[("I'm not overly clean nor messy", 'Neither'), ("I'm a more messy person", 'Messy'), ("I'm more of a clean person", 'Clean')], default="I'm not overly clean nor messy", max_length=100)),
                ('smoke_drink', models.CharField(choices=[('No, I do not', 'No'), ('Yes, I do', 'Yes')], default='No, I do not', max_length=100)),
                ('overnight', models.CharField(choices=[('No, I would not be okay with an overnight guest', 'No'), ('Yes, I would be okay with overnight guests', 'Yes')], default='No, I would not be okay with an overnight guest', max_length=100)),
                ('nightlife', models.CharField(choices=[('No, I do not like going out at night', 'No'), ('Yes, I go out at night', 'Yes')], default='No, I do not like going out at night', max_length=100)),
                ('study', models.CharField(choices=[('I prefer a quiet environment while studying', 'Quiet'), ("I don't mind noise or music while studying", 'Loud')], default='I prefer a quiet environment while studying', max_length=100)),
                ('where', models.CharField(choices=[('I want to live on-grounds', 'On Grounds'), ('I want to live off-grounds', 'Off Grounds'), ('I have no preference', 'No Pref')], default='I have no preference', max_length=100)),
                ('personality', models.CharField(choices=[('I am more introverted', 'Introvert'), ('I am more extroverted', 'Extrovert')], default='I am more introverted', max_length=100)),
                ('sharing', models.CharField(choices=[('I would be ok to share/borrow things from roommates', 'Yes'), ('I would not be ok to share/borrow things from roommates', 'No')], default='I would not be ok to share/borrow things from roommates', max_length=100)),
                ('gender', models.CharField(choices=[('I would be ok to have roomates of different genders', 'Yes'), ('I would not be ok to have roomates of different genders', 'No')], default='I would not be ok to have roomates of different genders', max_length=100)),
                ('year', models.CharField(choices=[('I only want to room with people my year', 'Yes'), ("I don't mind rooming with people of different years", 'No')], default="I don't mind rooming with people of different years", max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/images/noimage_rb51dj.png', upload_to='images/')),
                ('name', models.CharField(max_length=400)),
                ('bio', models.CharField(blank=True, default='', max_length=500)),
                ('pronouns', models.CharField(blank=True, default='', max_length=400)),
                ('age', models.PositiveIntegerField(blank=True, default=17)),
                ('year', models.PositiveIntegerField(blank=True, default=1)),
                ('schedule_image', models.ImageField(default='media/images/noschedule_zdconk.png', upload_to='images/')),
                ('dorm_pref', models.CharField(blank=True, choices=[('No preference.', 'None'), ('Hall-Style', 'Hall'), ('Suite-Style', 'Suite')], default='No preference.', max_length=100)),
                ('school', models.CharField(blank=True, choices=[('default', 'Default'), ('College and Graduate School of Arts and Sciences', 'College'), ('School of Engineering and Applied Science', 'Engineering'), ('School of Architecture', 'Architecture'), ('McIntire School of Commerce', 'Commerce'), ('School of Nursing', 'Nursing'), ('School of Medicine', 'Med'), ('School of Law', 'Law'), ('School of Education and Human Development', 'Education'), ('School of Data Science', 'Data Science'), ('School of Continuing & Professional Studies', 'Professional Studies'), ('Frank Batten School of Leadership and Public Policy', 'Leadership'), ('Darden School of Business', 'Business')], default='default', max_length=500)),
                ('roomates', models.PositiveIntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
