# Generated by Django 3.1.6 on 2021-04-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionthread',
            name='user',
        ),
    ]
