# Generated by Django 3.1.6 on 2021-04-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_discussionthread_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionthread',
            name='author',
            field=models.CharField(default='', max_length=300),
        ),
    ]
