# Generated by Django 3.1.6 on 2021-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210320_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=17),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dorm_pref',
            field=models.CharField(blank=True, choices=[('No preference.', 'None'), ('Hall-Style', 'Hall'), ('Suite-Style', 'Suite')], default='No preference.', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roomates',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('College and Graduate School of Arts and Sciences', 'College'), ('School of Engineering and Applied Science', 'Engineering'), ('School of Architecture', 'Architecture'), ('McIntire School of Commerce', 'Commerce'), ('School of Nursing', 'Nursing'), ('School of Medicine', 'Med'), ('School of Law', 'Law'), ('School of Education and Human Development', 'Education'), ('School of Data Science', 'Data Science'), ('School of Continuing & Professional Studies', 'Professional Studies'), ('Frank Batten School of Leadership and Public Policy', 'Leadership'), ('Darden School of Business', 'Business')], default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
