# Generated by Django 3.1.6 on 2021-04-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210405_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='blank-profile-picture-973460_1280_jslnqr.png', upload_to='images/'),
        ),
    ]
