# Generated by Django 3.1.6 on 2021-04-19 13:28

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_discussionthread_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='insta_handle',
            field=models.CharField(blank=True, default='@', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Enter phone number here', max_length=31),
        ),
        migrations.AddField(
            model_name='profile',
            name='snapchat_handle',
            field=models.CharField(blank=True, default='@', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_handle',
            field=models.CharField(blank=True, default='@', max_length=300),
        ),
    ]
