# Generated by Django 3.1.6 on 2021-03-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210323_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='schedule_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
