# Generated by Django 3.1.6 on 2021-04-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210405_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/images/blank-profile-picture-973460_1280_jslnqr.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='schedule_image',
            field=models.ImageField(default='media/images/noschedule_zdconk.png', upload_to='images/'),
        ),
    ]
