# Generated by Django 3.1.6 on 2021-04-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210419_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='insta_handle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='snapchat_handle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
