# Generated by Django 3.1.6 on 2021-04-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210405_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/images/blank-profile-picture-973460_1280_jslnqr.png', upload_to='images/'),
        ),
    ]
