# Generated by Django 3.1.6 on 2021-04-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210405_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/default_img_epaxjl.jpg', upload_to='images/'),
        ),
    ]
